"""Initial migration.

Revision ID: 54dcee894c22
Revises: 
Create Date: 2024-08-01 10:03:21.328886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision = '54dcee894c22'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the current engine and connect to the database
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)

    # Check if 'name' column exists in 'device' table
    columns = [col['name'] for col in inspector.get_columns('device')]
    if 'name' not in columns:
        op.add_column('device', sa.Column('name', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the current engine and connect to the database
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)

    # Check if 'name' column exists in 'device' table
    columns = [col['name'] for col in inspector.get_columns('device')]
    if 'name' in columns:
        op.drop_column('device', 'name')
    # ### end Alembic commands ###
